### PR TITLE
Fix reversed color

### LINKED ISSUE #49: Colors are reversed
That's how they look in firefox
Screenshot 2020-03-30 at 23 18 25

They seem to be ok in chrome

### PR DESCRIPTION
**Pull request by pastDexter**
Closes #49 

It was caused by this line in `confettConfig`:
```javascript
COLORS.sort((a, b) => Math.random())
```
1. `sort` mutates original array 
2. `sort` with `Math.random()` doesnt really shuffle an array
> 1.If compare (a,b) is less than zero, the sort( ) method sorts a to a lower index than b. In other words, a will come first.
2.If compare (a,b) is greater than zero, the sort( ) method sort b to a lower index than a, i.e., b will come first.
3.If compare (a,b) returns zero, the sort ( ) method considers a equals b and leaves their positions unchanged.

### CODE REVIEW

File: src/games/kalambury/board/GameBoard.js [hunk 1]
```diff
@@ -71,6 +72,11 @@ const GameBoard = ({
     if (isDrawing) moves.UpdateDrawing(lines);
   }, [isDrawing, moves, lines]);
 
+  const handleChangePhrase = () => {
+    ChangePhrase();
+    setLines([]);
+  };
+
```
Comment (turbaszek) [inline src/games/kalambury/board/GameBoard.js]: And this is unrelated change done in #54

Comment (pastDexter) [reply src/games/kalambury/board/GameBoard.js]: yep 🙈
